
services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: toko
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adamwahyukur
    restart: always

  backend:
    build: ./be
    container_name: backend-api
    ports:
      - "5000:5000"
    volumes:
      - ./be:/app
      - /app/node_modules
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:adamwahyukur@postgres:5432/toko
      - PORT=5000
      - NODE_ENV=development
    restart: always

  frontend:
    build: ./fe
    container_name: frontend-app
    ports:
      - "3000:3000"
    volumes:
      - ./fe:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000

volumes:
  postgres_data: