CREATE TABLE IF NOT EXISTS produk (
  id SERIAL PRIMARY KEY,
  nama_produk VARCHAR(255) NOT NULL,
  descripti_produk TEXT,
  price DECIMAL(10, 2) NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  image_url VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
